import turtle 
turtle.Screen().bgcolor("yellow")
turtle.Screen().setup(600,600)
polygon=turtle.Turtle()
polygon.forward(100)
polygon.left(72)
polygon.forward(100)
polygon.left(72)
polygon.forward(100)
polygon.left(72)
polygon.forward(100)
polygon.left(72)
polygon.forward(100)
turtle.done()