import turtle
turtle.Screen().bgcolor("orange")
turtle.Screen().setup(300,400)
square=turtle.Turtle()
square.forward(100)
square.left(90)
square.forward(100)
square.left(90)
square.forward(100)
square.left(90)
square.forward(100)
turtle.done()