from tkinter import*
widget=Tk()
widget.title("Getting started with widgets")
widget.geometry("500x400")
widget.configure(bg="lightblue")
headinglabel=Label(text="Registartion form",fg="white",bg="black")
headinglabel.pack()
namelabel=Label(text="Name-",fg="black")
namelabel.pack()
nameinput=Entry()
nameinput.pack()
agelabel=Label(text="Age-",fg="black")
agelabel.pack()
ageinput=Entry()
ageinput.pack()
gradelabel=Label(text="Grade-",fg="black")
gradelabel.pack()
gradeinput=Entry()
gradeinput.pack()
contactnumberlabel=Label(text="Contact number-",fg="black")
contactnumberlabel.pack()
contactnumberinput=Entry()
contactnumberinput.pack()
registrationbutton=Button(text="Click here to submit",height=2,width=15,fg="red",bg="yellow")
registrationbutton.pack()
clear=Button(text="clear all",height=1,width=10,fg="orange",bg="purple")
clear.pack()
widget.mainloop()
