from tkinter import*
widget=Tk()
widget.title("Getting started with widgets")
widget.geometry("500x700")
widget.configure(bg="lightblue")
headinglabel=Label(text="Registartion form",fg="white",bg="black")
headinglabel.pack()
namelabel=Label(text="Name-",fg="black")
namelabel.pack()
nameinput=Entry()
nameinput.pack()
genderlabel=Label(text="Gender-",fg="black")
genderlabel.pack()
genderinput=Entry()
genderinput.pack()
fathersnamelabel=Label(text="Father's name-",fg="black")
fathersnamelabel.pack()
fathersnameinput=Entry()
fathersnameinput.pack()
mothersnamelabel=Label(text="Mother's name-",fg="black")
mothersnamelabel.pack()
mothersnameinput=Entry()
mothersnameinput.pack()
agelabel=Label(text="Age-",fg="black")
agelabel.pack()
ageinput=Entry()
ageinput.pack()
gradelabel=Label(text="Grade-",fg="black")
gradelabel.pack()
gradeinput=Entry()
gradeinput.pack()
contactnumberlabel=Label(text="Contact number-",fg="black")
contactnumberlabel.pack()
contactnumberinput=Entry()
contactnumberinput.pack()
subject1label=Label(text="Subject1-",fg="black")
subject1label.pack()
subject1input=Entry()
subject1input.pack()
subject2label=Label(text="Subject2-",fg="black")
subject2label.pack()
subject2input=Entry()
subject2input.pack()
subject3label=Label(text="Subject3-",fg="black")
subject3label.pack()
subject3input=Entry()
subject3input.pack()
subject4label=Label(text="Subject4-",fg="black")
subject4label.pack()
subject4input=Entry()
subject4input.pack()
subject5label=Label(text="Subject5-",fg="black")
subject5label.pack()
subject5input=Entry()
subject5input.pack()
registrationbutton=Button(text="Click here to submit",height=2,width=15,fg="red",bg="yellow")
registrationbutton.pack()
clear=Button(text="clear all",height=1,width=10,fg="orange",bg="purple")
clear.pack()
widget.mainloop()
