from tkinter import*
widget=Tk()
widget.title("Getting started with widgets")
widget.geometry("270x500")
widget.configure(bg="lightblue")
headinglabel=Label(text="Registartion form",fg="white",bg="black")
headinglabel.place(x=60,y=10)
namelabel=Label(text="Name-",fg="black")
namelabel.place(x=60,y=40)
nameinput=Entry()
nameinput.place(x=120,y=40)
genderlabel=Label(text="Gender-",fg="black")
genderlabel.place(x=55,y=70)
genderinput=Entry()
genderinput.place(x=120,y=70)
fathersnamelabel=Label(text="Father's name-",fg="black")
fathersnamelabel.place(x=20,y=100)
fathersnameinput=Entry()
fathersnameinput.place(x=120,y=100)
mothersnamelabel=Label(text="Mother's name-",fg="black")
mothersnamelabel.place(x=14,y=130)
mothersnameinput=Entry()
mothersnameinput.place(x=120,y=130)
agelabel=Label(text="Age-",fg="black")
agelabel.place(x=73,y=160)
ageinput=Entry()
ageinput.place(x=120,y=160)
gradelabel=Label(text="Grade-",fg="black")
gradelabel.place(x=63,y=190)
gradeinput=Entry()
gradeinput.place(x=120,y=190)
contactnumberlabel=Label(text="Contact number-",fg="black")
contactnumberlabel.place(x=8,y=220)
contactnumberinput=Entry()
contactnumberinput.place(x=120,y=220)
subject1label=Label(text="Subject1-",fg="black")
subject1label.place(x=50,y=250)
subject1input=Entry()
subject1input.place(x=120,y=250)
subject2label=Label(text="Subject2-",fg="black")
subject2label.place(x=50,y=280)
subject2input=Entry()
subject2input.place(x=120,y=280)
subject3label=Label(text="Subject3-",fg="black")
subject3label.place(x=50,y=310)
subject3input=Entry()
subject3input.place(x=120,y=310)
subject4label=Label(text="Subject4-",fg="black")
subject4label.place(x=50,y=340)
subject4input=Entry()
subject4input.place(x=120,y=340)
subject5label=Label(text="Subject5-",fg="black")
subject5label.place(x=50,y=370)
subject5input=Entry()
subject5input.place(x=120,y=370)
registrationbutton=Button(text="Click here to submit",height=1,width=15,fg="red",bg="yellow")
registrationbutton.place(x=85,y=400)
clear=Button(text="clear all",height=1,width=15,fg="red",bg="yellow")
clear.place(x=85,y=430)
widget.mainloop()