class studentid:
    def __init__(self,name,age,grade,fathersname,mothersname,contactnumber):
        self.name=name
        self.age=age
        self.grade=grade
        self.fathersname=fathersname
        self.mothersname=mothersname
        self.contactnumber=contactnumber
student1=studentid('Swanith',12,7,'Srikanth','Shobha',9449083888)
print('Your name is',student1.name)
print('Your age is',student1.age)
print('Your grade is',student1.grade)
print('Your fathers name  is',student1.fathersname)
print('Your mothers name is',student1.mothersname)
print('Your contact number is',student1.contactnumber)
student2=studentid('Pranav',14,9,'Niranjan','Anuradha',9340325647)
print('Your name is',student2.name)
print('Your age is',student2.age)
print('Your grade is',student2.grade)
print('Your fathers name  is',student2.fathersname)
print('Your mothers name is',student2.mothersname)
print('Your contact number is',student2.contactnumber)
student3=studentid('Aryan',15,10,'Pradeep','Shubha',9367248154)
print('Your name is',student3.name)
print('Your age is',student3.age)
print('Your grade is',student3.grade)
print('Your fathers name  is',student3.fathersname)
print('Your mothers name is',student3.mothersname)
print('Your contact number is',student3.contactnumber)
student4=studentid('Vachan',13,8,'Praveen','Sheela',7022639939)
print('Your name is',student4.name)
print('Your age is',student4.age)
print('Your grade is',student4.grade)
print('Your fathers name  is',student4.fathersname)
print('Your mothers name is',student4.mothersname)
print('Your contact number is',student4.contactnumber)
student5=studentid('Danvin',10,5,'Suman','Asha',9836342546)
print('Your name is',student5.name)
print('Your age is',student5.age)
print('Your grade is',student5.grade)
print('Your fathers name  is',student5.fathersname)
print('Your mothers name is',student5.mothersname)
print('Your contact number is',student5.contactnumber)
student6=studentid('Pushkar',12,7,'Yashas','Jeevita',7345923656)
print('Your name is',student6.name)
print('Your age is',student6.age)
print('Your grade is',student6.grade)
print('Your fathers name  is',student6.fathersname)
print('Your mothers name is',student6.mothersname)
print('Your contact number is',student6.contactnumber)